version: '3.8'
services:
  rustddd-microservices-redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --loglevel warning --requirepass rustddd
    volumes:
      - ./data:/data
