version: "3.5"
services:
  rustddd-nginx:
    image: nginx:latest
    container_name: rustddd-nginx
    network_mode: "host"
    ports:
      - 3000:3000
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
