version: "3.5"

services:
  rustddd-jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: rustddd-jaeger
    ports:
      - "6831:6831/udp" # UDP port for Jaeger agent
      - "16686:16686" # Web UI
      - "14268:14268" # HTTP port for spans
      - "4317:4317" # OTLP gRPC receiver
